package com.pb;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required int32 score = 4;</code>
     */
    boolean hasScore();
    /**
     * <code>required int32 score = 4;</code>
     */
    int getScore();

    /**
     * <code>optional string author = 5;</code>
     */
    boolean hasAuthor();
    /**
     * <code>optional string author = 5;</code>
     */
    java.lang.String getAuthor();
    /**
     * <code>optional string author = 5;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    java.util.List<Person.Task.Answer> 
        getAnswerList();
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    Person.Task.Answer getAnswer(int index);
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    int getAnswerCount();
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    java.util.List<? extends Person.Task.AnswerOrBuilder> 
        getAnswerOrBuilderList();
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    Person.Task.AnswerOrBuilder getAnswerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Task extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Task)
      TaskOrBuilder {
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Task(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Task defaultInstance;
    public static Task getDefaultInstance() {
      return defaultInstance;
    }

    public Task getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              content_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              score_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              author_ = bs;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                answer_ = new java.util.ArrayList<Person.Task.Answer>();
                mutable_bitField0_ |= 0x00000020;
              }
              answer_.add(input.readMessage(Person.Task.Answer.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          answer_ = java.util.Collections.unmodifiableList(answer_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_Task_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.Task.class, Person.Task.Builder.class);
    }

    public static com.google.protobuf.Parser<Task> PARSER =
        new com.google.protobuf.AbstractParser<Task>() {
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Task.AnswerType}
     */
    public enum AnswerType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STRING = 0;</code>
       */
      STRING(0, 0),
      /**
       * <code>INT = 1;</code>
       */
      INT(1, 1),
      /**
       * <code>DOUBLE = 2;</code>
       */
      DOUBLE(2, 2),
      ;

      /**
       * <code>STRING = 0;</code>
       */
      public static final int STRING_VALUE = 0;
      /**
       * <code>INT = 1;</code>
       */
      public static final int INT_VALUE = 1;
      /**
       * <code>DOUBLE = 2;</code>
       */
      public static final int DOUBLE_VALUE = 2;


      public final int getNumber() { return value; }

      public static AnswerType valueOf(int value) {
        switch (value) {
          case 0: return STRING;
          case 1: return INT;
          case 2: return DOUBLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AnswerType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AnswerType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AnswerType>() {
              public AnswerType findValueByNumber(int number) {
                return AnswerType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Person.Task.getDescriptor().getEnumTypes().get(0);
      }

      private static final AnswerType[] VALUES = values();

      public static AnswerType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private AnswerType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Task.AnswerType)
    }

    public interface AnswerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Task.Answer)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 data = 1;</code>
       */
      boolean hasData();
      /**
       * <code>required int32 data = 1;</code>
       */
      int getData();

      /**
       * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
       */
      boolean hasType();
      /**
       * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
       */
      Person.Task.AnswerType getType();
    }
    /**
     * Protobuf type {@code Task.Answer}
     */
    public static final class Answer extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Task.Answer)
        AnswerOrBuilder {
      // Use Answer.newBuilder() to construct.
      private Answer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Answer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Answer defaultInstance;
      public static Answer getDefaultInstance() {
        return defaultInstance;
      }

      public Answer getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Answer(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                data_ = input.readInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                Person.Task.AnswerType value = Person.Task.AnswerType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_Task_Answer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_Task_Answer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.Task.Answer.class, Person.Task.Answer.Builder.class);
      }

      public static com.google.protobuf.Parser<Answer> PARSER =
          new com.google.protobuf.AbstractParser<Answer>() {
        public Answer parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Answer(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Answer> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DATA_FIELD_NUMBER = 1;
      private int data_;
      /**
       * <code>required int32 data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 data = 1;</code>
       */
      public int getData() {
        return data_;
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private Person.Task.AnswerType type_;
      /**
       * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
       */
      public Person.Task.AnswerType getType() {
        return type_;
      }

      private void initFields() {
        data_ = 0;
        type_ = Person.Task.AnswerType.INT;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasData()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, data_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, data_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Person.Task.Answer parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Person.Task.Answer parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Person.Task.Answer parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Person.Task.Answer parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Person.Task.Answer parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Person.Task.Answer parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Person.Task.Answer parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Person.Task.Answer parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Person.Task.Answer parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Person.Task.Answer parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Person.Task.Answer prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Task.Answer}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Task.Answer)
          Person.Task.AnswerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Person.internal_static_Task_Answer_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Person.internal_static_Task_Answer_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Person.Task.Answer.class, Person.Task.Answer.Builder.class);
        }

        // Construct using Person.Task.Answer.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          data_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = Person.Task.AnswerType.INT;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Person.internal_static_Task_Answer_descriptor;
        }

        public Person.Task.Answer getDefaultInstanceForType() {
          return Person.Task.Answer.getDefaultInstance();
        }

        public Person.Task.Answer build() {
          Person.Task.Answer result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Person.Task.Answer buildPartial() {
          Person.Task.Answer result = new Person.Task.Answer(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.data_ = data_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Person.Task.Answer) {
            return mergeFrom((Person.Task.Answer)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Person.Task.Answer other) {
          if (other == Person.Task.Answer.getDefaultInstance()) return this;
          if (other.hasData()) {
            setData(other.getData());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasData()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Person.Task.Answer parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Person.Task.Answer) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int data_ ;
        /**
         * <code>required int32 data = 1;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 data = 1;</code>
         */
        public int getData() {
          return data_;
        }
        /**
         * <code>required int32 data = 1;</code>
         */
        public Builder setData(int value) {
          bitField0_ |= 0x00000001;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 data = 1;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000001);
          data_ = 0;
          onChanged();
          return this;
        }

        private Person.Task.AnswerType type_ = Person.Task.AnswerType.INT;
        /**
         * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
         */
        public Person.Task.AnswerType getType() {
          return type_;
        }
        /**
         * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
         */
        public Builder setType(Person.Task.AnswerType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Task.AnswerType type = 2 [default = INT];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = Person.Task.AnswerType.INT;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Task.Answer)
      }

      static {
        defaultInstance = new Answer(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Task.Answer)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 4;
    private int score_;
    /**
     * <code>required int32 score = 4;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 score = 4;</code>
     */
    public int getScore() {
      return score_;
    }

    public static final int AUTHOR_FIELD_NUMBER = 5;
    private java.lang.Object author_;
    /**
     * <code>optional string author = 5;</code>
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string author = 5;</code>
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          author_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string author = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWER_FIELD_NUMBER = 6;
    private java.util.List<Person.Task.Answer> answer_;
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    public java.util.List<Person.Task.Answer> getAnswerList() {
      return answer_;
    }
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    public java.util.List<? extends Person.Task.AnswerOrBuilder> 
        getAnswerOrBuilderList() {
      return answer_;
    }
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    public int getAnswerCount() {
      return answer_.size();
    }
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    public Person.Task.Answer getAnswer(int index) {
      return answer_.get(index);
    }
    /**
     * <code>repeated .Task.Answer answer = 6;</code>
     */
    public Person.Task.AnswerOrBuilder getAnswerOrBuilder(
        int index) {
      return answer_.get(index);
    }

    private void initFields() {
      id_ = 0;
      title_ = "";
      content_ = "";
      score_ = 0;
      author_ = "";
      answer_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAnswerCount(); i++) {
        if (!getAnswer(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, score_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAuthorBytes());
      }
      for (int i = 0; i < answer_.size(); i++) {
        output.writeMessage(6, answer_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, score_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAuthorBytes());
      }
      for (int i = 0; i < answer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, answer_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Person.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Person.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Person.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Person.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Person.Task prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Task)
        Person.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_Task_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.Task.class, Person.Task.Builder.class);
      }

      // Construct using Person.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAnswerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (answerBuilder_ == null) {
          answer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          answerBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_Task_descriptor;
      }

      public Person.Task getDefaultInstanceForType() {
        return Person.Task.getDefaultInstance();
      }

      public Person.Task build() {
        Person.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person.Task buildPartial() {
        Person.Task result = new Person.Task(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.author_ = author_;
        if (answerBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            answer_ = java.util.Collections.unmodifiableList(answer_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.answer_ = answer_;
        } else {
          result.answer_ = answerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.Task) {
          return mergeFrom((Person.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.Task other) {
        if (other == Person.Task.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasAuthor()) {
          bitField0_ |= 0x00000010;
          author_ = other.author_;
          onChanged();
        }
        if (answerBuilder_ == null) {
          if (!other.answer_.isEmpty()) {
            if (answer_.isEmpty()) {
              answer_ = other.answer_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureAnswerIsMutable();
              answer_.addAll(other.answer_);
            }
            onChanged();
          }
        } else {
          if (!other.answer_.isEmpty()) {
            if (answerBuilder_.isEmpty()) {
              answerBuilder_.dispose();
              answerBuilder_ = null;
              answer_ = other.answer_;
              bitField0_ = (bitField0_ & ~0x00000020);
              answerBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAnswerFieldBuilder() : null;
            } else {
              answerBuilder_.addAllMessages(other.answer_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        for (int i = 0; i < getAnswerCount(); i++) {
          if (!getAnswer(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.Task) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <code>required int32 score = 4;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 score = 4;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>required int32 score = 4;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000008;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 score = 4;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000008);
        score_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>optional string author = 5;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string author = 5;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            author_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string author = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string author = 5;</code>
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 5;</code>
       */
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 5;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        author_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Person.Task.Answer> answer_ =
        java.util.Collections.emptyList();
      private void ensureAnswerIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          answer_ = new java.util.ArrayList<Person.Task.Answer>(answer_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Person.Task.Answer, Person.Task.Answer.Builder, Person.Task.AnswerOrBuilder> answerBuilder_;

      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public java.util.List<Person.Task.Answer> getAnswerList() {
        if (answerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(answer_);
        } else {
          return answerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public int getAnswerCount() {
        if (answerBuilder_ == null) {
          return answer_.size();
        } else {
          return answerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Person.Task.Answer getAnswer(int index) {
        if (answerBuilder_ == null) {
          return answer_.get(index);
        } else {
          return answerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder setAnswer(
          int index, Person.Task.Answer value) {
        if (answerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnswerIsMutable();
          answer_.set(index, value);
          onChanged();
        } else {
          answerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder setAnswer(
          int index, Person.Task.Answer.Builder builderForValue) {
        if (answerBuilder_ == null) {
          ensureAnswerIsMutable();
          answer_.set(index, builderForValue.build());
          onChanged();
        } else {
          answerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder addAnswer(Person.Task.Answer value) {
        if (answerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnswerIsMutable();
          answer_.add(value);
          onChanged();
        } else {
          answerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder addAnswer(
          int index, Person.Task.Answer value) {
        if (answerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnswerIsMutable();
          answer_.add(index, value);
          onChanged();
        } else {
          answerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder addAnswer(
          Person.Task.Answer.Builder builderForValue) {
        if (answerBuilder_ == null) {
          ensureAnswerIsMutable();
          answer_.add(builderForValue.build());
          onChanged();
        } else {
          answerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder addAnswer(
          int index, Person.Task.Answer.Builder builderForValue) {
        if (answerBuilder_ == null) {
          ensureAnswerIsMutable();
          answer_.add(index, builderForValue.build());
          onChanged();
        } else {
          answerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder addAllAnswer(
          java.lang.Iterable<? extends Person.Task.Answer> values) {
        if (answerBuilder_ == null) {
          ensureAnswerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, answer_);
          onChanged();
        } else {
          answerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder clearAnswer() {
        if (answerBuilder_ == null) {
          answer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          answerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Builder removeAnswer(int index) {
        if (answerBuilder_ == null) {
          ensureAnswerIsMutable();
          answer_.remove(index);
          onChanged();
        } else {
          answerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Person.Task.Answer.Builder getAnswerBuilder(
          int index) {
        return getAnswerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Person.Task.AnswerOrBuilder getAnswerOrBuilder(
          int index) {
        if (answerBuilder_ == null) {
          return answer_.get(index);  } else {
          return answerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public java.util.List<? extends Person.Task.AnswerOrBuilder> 
           getAnswerOrBuilderList() {
        if (answerBuilder_ != null) {
          return answerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(answer_);
        }
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Person.Task.Answer.Builder addAnswerBuilder() {
        return getAnswerFieldBuilder().addBuilder(
            Person.Task.Answer.getDefaultInstance());
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public Person.Task.Answer.Builder addAnswerBuilder(
          int index) {
        return getAnswerFieldBuilder().addBuilder(
            index, Person.Task.Answer.getDefaultInstance());
      }
      /**
       * <code>repeated .Task.Answer answer = 6;</code>
       */
      public java.util.List<Person.Task.Answer.Builder> 
           getAnswerBuilderList() {
        return getAnswerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Person.Task.Answer, Person.Task.Answer.Builder, Person.Task.AnswerOrBuilder> 
          getAnswerFieldBuilder() {
        if (answerBuilder_ == null) {
          answerBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Person.Task.Answer, Person.Task.Answer.Builder, Person.Task.AnswerOrBuilder>(
                  answer_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          answer_ = null;
        }
        return answerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Task)
    }

    static {
      defaultInstance = new Task(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Task)
  }

  public interface AddTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Task task = 1;</code>
     */
    java.util.List<Person.Task> 
        getTaskList();
    /**
     * <code>repeated .Task task = 1;</code>
     */
    Person.Task getTask(int index);
    /**
     * <code>repeated .Task task = 1;</code>
     */
    int getTaskCount();
    /**
     * <code>repeated .Task task = 1;</code>
     */
    java.util.List<? extends Person.TaskOrBuilder> 
        getTaskOrBuilderList();
    /**
     * <code>repeated .Task task = 1;</code>
     */
    Person.TaskOrBuilder getTaskOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AddTask}
   */
  public static final class AddTask extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AddTask)
      AddTaskOrBuilder {
    // Use AddTask.newBuilder() to construct.
    private AddTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddTask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddTask defaultInstance;
    public static AddTask getDefaultInstance() {
      return defaultInstance;
    }

    public AddTask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                task_ = new java.util.ArrayList<Person.Task>();
                mutable_bitField0_ |= 0x00000001;
              }
              task_.add(input.readMessage(Person.Task.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          task_ = java.util.Collections.unmodifiableList(task_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_AddTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_AddTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.AddTask.class, Person.AddTask.Builder.class);
    }

    public static com.google.protobuf.Parser<AddTask> PARSER =
        new com.google.protobuf.AbstractParser<AddTask>() {
      public AddTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddTask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddTask> getParserForType() {
      return PARSER;
    }

    public static final int TASK_FIELD_NUMBER = 1;
    private java.util.List<Person.Task> task_;
    /**
     * <code>repeated .Task task = 1;</code>
     */
    public java.util.List<Person.Task> getTaskList() {
      return task_;
    }
    /**
     * <code>repeated .Task task = 1;</code>
     */
    public java.util.List<? extends Person.TaskOrBuilder> 
        getTaskOrBuilderList() {
      return task_;
    }
    /**
     * <code>repeated .Task task = 1;</code>
     */
    public int getTaskCount() {
      return task_.size();
    }
    /**
     * <code>repeated .Task task = 1;</code>
     */
    public Person.Task getTask(int index) {
      return task_.get(index);
    }
    /**
     * <code>repeated .Task task = 1;</code>
     */
    public Person.TaskOrBuilder getTaskOrBuilder(
        int index) {
      return task_.get(index);
    }

    private void initFields() {
      task_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getTaskCount(); i++) {
        if (!getTask(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < task_.size(); i++) {
        output.writeMessage(1, task_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < task_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, task_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Person.AddTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.AddTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.AddTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.AddTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.AddTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person.AddTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Person.AddTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Person.AddTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Person.AddTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person.AddTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Person.AddTask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddTask)
        Person.AddTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_AddTask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_AddTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.AddTask.class, Person.AddTask.Builder.class);
      }

      // Construct using Person.AddTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTaskFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (taskBuilder_ == null) {
          task_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          taskBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_AddTask_descriptor;
      }

      public Person.AddTask getDefaultInstanceForType() {
        return Person.AddTask.getDefaultInstance();
      }

      public Person.AddTask build() {
        Person.AddTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person.AddTask buildPartial() {
        Person.AddTask result = new Person.AddTask(this);
        int from_bitField0_ = bitField0_;
        if (taskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            task_ = java.util.Collections.unmodifiableList(task_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.task_ = task_;
        } else {
          result.task_ = taskBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.AddTask) {
          return mergeFrom((Person.AddTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.AddTask other) {
        if (other == Person.AddTask.getDefaultInstance()) return this;
        if (taskBuilder_ == null) {
          if (!other.task_.isEmpty()) {
            if (task_.isEmpty()) {
              task_ = other.task_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTaskIsMutable();
              task_.addAll(other.task_);
            }
            onChanged();
          }
        } else {
          if (!other.task_.isEmpty()) {
            if (taskBuilder_.isEmpty()) {
              taskBuilder_.dispose();
              taskBuilder_ = null;
              task_ = other.task_;
              bitField0_ = (bitField0_ & ~0x00000001);
              taskBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTaskFieldBuilder() : null;
            } else {
              taskBuilder_.addAllMessages(other.task_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTaskCount(); i++) {
          if (!getTask(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.AddTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.AddTask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Person.Task> task_ =
        java.util.Collections.emptyList();
      private void ensureTaskIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          task_ = new java.util.ArrayList<Person.Task>(task_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Person.Task, Person.Task.Builder, Person.TaskOrBuilder> taskBuilder_;

      /**
       * <code>repeated .Task task = 1;</code>
       */
      public java.util.List<Person.Task> getTaskList() {
        if (taskBuilder_ == null) {
          return java.util.Collections.unmodifiableList(task_);
        } else {
          return taskBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public int getTaskCount() {
        if (taskBuilder_ == null) {
          return task_.size();
        } else {
          return taskBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Person.Task getTask(int index) {
        if (taskBuilder_ == null) {
          return task_.get(index);
        } else {
          return taskBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder setTask(
          int index, Person.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.set(index, value);
          onChanged();
        } else {
          taskBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder setTask(
          int index, Person.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.set(index, builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder addTask(Person.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.add(value);
          onChanged();
        } else {
          taskBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder addTask(
          int index, Person.Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.add(index, value);
          onChanged();
        } else {
          taskBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder addTask(
          Person.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.add(builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder addTask(
          int index, Person.Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.add(index, builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder addAllTask(
          java.lang.Iterable<? extends Person.Task> values) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, task_);
          onChanged();
        } else {
          taskBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder clearTask() {
        if (taskBuilder_ == null) {
          task_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          taskBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Builder removeTask(int index) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.remove(index);
          onChanged();
        } else {
          taskBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Person.Task.Builder getTaskBuilder(
          int index) {
        return getTaskFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Person.TaskOrBuilder getTaskOrBuilder(
          int index) {
        if (taskBuilder_ == null) {
          return task_.get(index);  } else {
          return taskBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public java.util.List<? extends Person.TaskOrBuilder> 
           getTaskOrBuilderList() {
        if (taskBuilder_ != null) {
          return taskBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(task_);
        }
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Person.Task.Builder addTaskBuilder() {
        return getTaskFieldBuilder().addBuilder(
            Person.Task.getDefaultInstance());
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public Person.Task.Builder addTaskBuilder(
          int index) {
        return getTaskFieldBuilder().addBuilder(
            index, Person.Task.getDefaultInstance());
      }
      /**
       * <code>repeated .Task task = 1;</code>
       */
      public java.util.List<Person.Task.Builder> 
           getTaskBuilderList() {
        return getTaskFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Person.Task, Person.Task.Builder, Person.TaskOrBuilder> 
          getTaskFieldBuilder() {
        if (taskBuilder_ == null) {
          taskBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Person.Task, Person.Task.Builder, Person.TaskOrBuilder>(
                  task_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          task_ = null;
        }
        return taskBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:AddTask)
    }

    static {
      defaultInstance = new AddTask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddTask)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_Answer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Task_Answer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddTask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\"\333\001\n\004Task\022\n\n\002id\030\001 \002(\005\022\r\n\005t" +
      "itle\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\r\n\005score\030\004 \002" +
      "(\005\022\016\n\006author\030\005 \001(\t\022\034\n\006answer\030\006 \003(\0132\014.Tas" +
      "k.Answer\032;\n\006Answer\022\014\n\004data\030\001 \002(\005\022#\n\004type" +
      "\030\002 \001(\0162\020.Task.AnswerType:\003INT\"-\n\nAnswerT" +
      "ype\022\n\n\006STRING\020\000\022\007\n\003INT\020\001\022\n\n\006DOUBLE\020\002\"\036\n\007" +
      "AddTask\022\023\n\004task\030\001 \003(\0132\005.Task"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Task_descriptor,
        new java.lang.String[] { "Id", "Title", "Content", "Score", "Author", "Answer", });
    internal_static_Task_Answer_descriptor =
      internal_static_Task_descriptor.getNestedTypes().get(0);
    internal_static_Task_Answer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Task_Answer_descriptor,
        new java.lang.String[] { "Data", "Type", });
    internal_static_AddTask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddTask_descriptor,
        new java.lang.String[] { "Task", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
